name: Node.js/React CI/CD
on: 
  pull_request:
    branches:
      [master]
  push:
    branches:
      [master]
  
jobs:
  build:
    runs-on: windows 10
    steps:
    - uses: actions/checkout@v2
    - name: Using Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
    - name: Install dependencies, build and test
      run: |
        npm install
        npm run build
        npm run test
    - name: Using React.js
      run: npm start
    - name: Run tests

      run: npm test 

