name: Node.js/React.js-CI/CD
on: 
  pull_request:
    branches:
      ['master','main']
  push:
    branches:
      ['master','main']
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Using Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20.
    - name: run install, build and test
      run: |
        npm install
        npm run build
        npm run test
      

